name: lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v1
      with:
        version: '3.3.6'

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v1
      with:
        path: '["hoauth2/src/", "hoauth2-example/src/"]'
        fail-on: warning
